// This file is generated by the rs-bump-version script

#pragma once

#include <array>
#include <string>

namespace RS::Intervals {

    inline std::array<int, 3> version() noexcept {
        return {{ 0, 2, 3 }};
    }

    inline std::string version_string() {
        return "0.2.3";
    }

}
