#include "rs-interval.hpp"
#include "test/unit-test.hpp"

using namespace RS::Intervals;
using namespace RS::Intervals::Detail;

using B = Boundary<int>;
using IB = IntervalBound;

namespace RS::Intervals::Detail {

    // Temporary work

    template <typename T>
    Boundary<T> operator+(const Boundary<T>& l, const Boundary<T>& r) {
        // TODO
        (void)l;
        (void)r;
        return {};
    }

}

void test_rs_interval_boundary_addition() {

    B el1(1, IB::empty, false);    B el2(2, IB::empty, false);
    B eu1(1, IB::empty, true);     B eu2(2, IB::empty, true);
    B cl1(1, IB::closed, false);   B cl2(2, IB::closed, false);
    B cu1(1, IB::closed, true);    B cu2(2, IB::closed, true);
    B ol1(1, IB::open, false);     B ol2(2, IB::open, false);
    B ou1(1, IB::open, true);      B ou2(2, IB::open, true);
    B ul1(1, IB::unbound, false);  B ul2(2, IB::unbound, false);
    B uu1(1, IB::unbound, true);   B uu2(2, IB::unbound, true);

    /* lb=0=empty    rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(el1, el2), 0);
    /* lb=0=empty    rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(el1, el1), 0);
    /* lb=0=empty    rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(el2, el1), 0);
    /* lb=0=empty    rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(el1, eu2), 0);
    /* lb=0=empty    rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(el1, eu1), 0);
    /* lb=0=empty    rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(el2, eu1), 0);
    /* lb=0=empty    rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(eu1, el2), 0);
    /* lb=0=empty    rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(eu1, el1), 0);
    /* lb=0=empty    rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(eu2, el1), 0);
    /* lb=0=empty    rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(eu1, eu2), 0);
    /* lb=0=empty    rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(eu1, eu1), 0);
    /* lb=0=empty    rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(eu2, eu1), 0);
    /* lb=0=empty    rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(el1, cl2), -1);
    /* lb=0=empty    rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(el1, cl1), -1);
    /* lb=0=empty    rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(el2, cl1), -1);
    /* lb=0=empty    rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(el1, cu2), -1);
    /* lb=0=empty    rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(el1, cu1), -1);
    /* lb=0=empty    rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(el2, cu1), -1);
    /* lb=0=empty    rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(eu1, cl2), 1);
    /* lb=0=empty    rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(eu1, cl1), 1);
    /* lb=0=empty    rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(eu2, cl1), 1);
    /* lb=0=empty    rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(eu1, cu2), 1);
    /* lb=0=empty    rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(eu1, cu1), 1);
    /* lb=0=empty    rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(eu2, cu1), 1);
    /* lb=0=empty    rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(el1, ol2), -1);
    /* lb=0=empty    rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(el1, ol1), -1);
    /* lb=0=empty    rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(el2, ol1), -1);
    /* lb=0=empty    rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(el1, ou2), -1);
    /* lb=0=empty    rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(el1, ou1), -1);
    /* lb=0=empty    rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(el2, ou1), -1);
    /* lb=0=empty    rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(eu1, ol2), 1);
    /* lb=0=empty    rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(eu1, ol1), 1);
    /* lb=0=empty    rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(eu2, ol1), 1);
    /* lb=0=empty    rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(eu1, ou2), 1);
    /* lb=0=empty    rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(eu1, ou1), 1);
    /* lb=0=empty    rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(eu2, ou1), 1);
    /* lb=0=empty    rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(el1, ul2), -1);
    /* lb=0=empty    rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(el1, ul1), -1);
    /* lb=0=empty    rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(el2, ul1), -1);
    /* lb=0=empty    rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(el1, uu2), -1);
    /* lb=0=empty    rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(el1, uu1), -1);
    /* lb=0=empty    rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(el2, uu1), -1);
    /* lb=0=empty    rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(eu1, ul2), 1);
    /* lb=0=empty    rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(eu1, ul1), 1);
    /* lb=0=empty    rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(eu2, ul1), 1);
    /* lb=0=empty    rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(eu1, uu2), 1);
    /* lb=0=empty    rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(eu1, uu1), 1);
    /* lb=0=empty    rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(eu2, uu1), 1);
    /* lb=1=closed   rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(cl1, el2), 1);
    /* lb=1=closed   rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(cl1, el1), 1);
    /* lb=1=closed   rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(cl2, el1), 1);
    /* lb=1=closed   rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(cl1, eu2), -1);
    /* lb=1=closed   rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(cl1, eu1), -1);
    /* lb=1=closed   rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(cl2, eu1), -1);
    /* lb=1=closed   rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(cu1, el2), 1);
    /* lb=1=closed   rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(cu1, el1), 1);
    /* lb=1=closed   rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(cu2, el1), 1);
    /* lb=1=closed   rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(cu1, eu2), -1);
    /* lb=1=closed   rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(cu1, eu1), -1);
    /* lb=1=closed   rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(cu2, eu1), -1);
    /* lb=1=closed   rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(cl1, cl2), -1);
    /* lb=1=closed   rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(cl1, cl1), 0);
    /* lb=1=closed   rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(cl2, cl1), 1);
    /* lb=1=closed   rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(cl1, cu2), -1);
    /* lb=1=closed   rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(cl1, cu1), 0);
    /* lb=1=closed   rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(cl2, cu1), 1);
    /* lb=1=closed   rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(cu1, cl2), -1);
    /* lb=1=closed   rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(cu1, cl1), 0);
    /* lb=1=closed   rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(cu2, cl1), 1);
    /* lb=1=closed   rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(cu1, cu2), -1);
    /* lb=1=closed   rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(cu1, cu1), 0);
    /* lb=1=closed   rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(cu2, cu1), 1);
    /* lb=1=closed   rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(cl1, ol2), -1);
    /* lb=1=closed   rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(cl1, ol1), -1);
    /* lb=1=closed   rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(cl2, ol1), 1);
    /* lb=1=closed   rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(cl1, ou2), -1);
    /* lb=1=closed   rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(cl1, ou1), 1);
    /* lb=1=closed   rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(cl2, ou1), 1);
    /* lb=1=closed   rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(cu1, ol2), -1);
    /* lb=1=closed   rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(cu1, ol1), -1);
    /* lb=1=closed   rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(cu2, ol1), 1);
    /* lb=1=closed   rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(cu1, ou2), -1);
    /* lb=1=closed   rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(cu1, ou1), 1);
    /* lb=1=closed   rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(cu2, ou1), 1);
    /* lb=1=closed   rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(cl1, ul2), 1);
    /* lb=1=closed   rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(cl1, ul1), 1);
    /* lb=1=closed   rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(cl2, ul1), 1);
    /* lb=1=closed   rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(cl1, uu2), -1);
    /* lb=1=closed   rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(cl1, uu1), -1);
    /* lb=1=closed   rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(cl2, uu1), -1);
    /* lb=1=closed   rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(cu1, ul2), 1);
    /* lb=1=closed   rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(cu1, ul1), 1);
    /* lb=1=closed   rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(cu2, ul1), 1);
    /* lb=1=closed   rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(cu1, uu2), -1);
    /* lb=1=closed   rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(cu1, uu1), -1);
    /* lb=1=closed   rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(cu2, uu1), -1);
    /* lb=2=open     rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(ol1, el2), 1);
    /* lb=2=open     rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(ol1, el1), 1);
    /* lb=2=open     rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(ol2, el1), 1);
    /* lb=2=open     rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(ol1, eu2), -1);
    /* lb=2=open     rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(ol1, eu1), -1);
    /* lb=2=open     rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(ol2, eu1), -1);
    /* lb=2=open     rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(ou1, el2), 1);
    /* lb=2=open     rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(ou1, el1), 1);
    /* lb=2=open     rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(ou2, el1), 1);
    /* lb=2=open     rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(ou1, eu2), -1);
    /* lb=2=open     rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(ou1, eu1), -1);
    /* lb=2=open     rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(ou2, eu1), -1);
    /* lb=2=open     rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(ol1, cl2), -1);
    /* lb=2=open     rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(ol1, cl1), 1);
    /* lb=2=open     rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(ol2, cl1), 1);
    /* lb=2=open     rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(ol1, cu2), -1);
    /* lb=2=open     rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(ol1, cu1), 1);
    /* lb=2=open     rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(ol2, cu1), 1);
    /* lb=2=open     rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(ou1, cl2), -1);
    /* lb=2=open     rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(ou1, cl1), -1);
    /* lb=2=open     rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(ou2, cl1), 1);
    /* lb=2=open     rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(ou1, cu2), -1);
    /* lb=2=open     rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(ou1, cu1), -1);
    /* lb=2=open     rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(ou2, cu1), 1);
    /* lb=2=open     rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(ol1, ol2), -1);
    /* lb=2=open     rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(ol1, ol1), 0);
    /* lb=2=open     rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(ol2, ol1), 1);
    /* lb=2=open     rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(ol1, ou2), -1);
    /* lb=2=open     rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(ol1, ou1), 1);
    /* lb=2=open     rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(ol2, ou1), 1);
    /* lb=2=open     rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(ou1, ol2), -1);
    /* lb=2=open     rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(ou1, ol1), -1);
    /* lb=2=open     rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(ou2, ol1), 1);
    /* lb=2=open     rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(ou1, ou2), -1);
    /* lb=2=open     rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(ou1, ou1), 0);
    /* lb=2=open     rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(ou2, ou1), 1);
    /* lb=2=open     rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(ol1, ul2), 1);
    /* lb=2=open     rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(ol1, ul1), 1);
    /* lb=2=open     rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(ol2, ul1), 1);
    /* lb=2=open     rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(ol1, uu2), -1);
    /* lb=2=open     rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(ol1, uu1), -1);
    /* lb=2=open     rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(ol2, uu1), -1);
    /* lb=2=open     rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(ou1, ul2), 1);
    /* lb=2=open     rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(ou1, ul1), 1);
    /* lb=2=open     rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(ou2, ul1), 1);
    /* lb=2=open     rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(ou1, uu2), -1);
    /* lb=2=open     rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(ou1, uu1), -1);
    /* lb=2=open     rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(ou2, uu1), -1);
    /* lb=3=unbound  rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(ul1, el2), 1);
    /* lb=3=unbound  rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(ul1, el1), 1);
    /* lb=3=unbound  rb=0=empty    !lu  !ru  */  //TEST_EQUAL(B::compare(ul2, el1), 1);
    /* lb=3=unbound  rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(ul1, eu2), -1);
    /* lb=3=unbound  rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(ul1, eu1), -1);
    /* lb=3=unbound  rb=0=empty    !lu  ru   */  //TEST_EQUAL(B::compare(ul2, eu1), -1);
    /* lb=3=unbound  rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(uu1, el2), 1);
    /* lb=3=unbound  rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(uu1, el1), 1);
    /* lb=3=unbound  rb=0=empty    lu   !ru  */  //TEST_EQUAL(B::compare(uu2, el1), 1);
    /* lb=3=unbound  rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(uu1, eu2), -1);
    /* lb=3=unbound  rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(uu1, eu1), -1);
    /* lb=3=unbound  rb=0=empty    lu   ru   */  //TEST_EQUAL(B::compare(uu2, eu1), -1);
    /* lb=3=unbound  rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(ul1, cl2), -1);
    /* lb=3=unbound  rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(ul1, cl1), -1);
    /* lb=3=unbound  rb=1=closed   !lu  !ru  */  //TEST_EQUAL(B::compare(ul2, cl1), -1);
    /* lb=3=unbound  rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(ul1, cu2), -1);
    /* lb=3=unbound  rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(ul1, cu1), -1);
    /* lb=3=unbound  rb=1=closed   !lu  ru   */  //TEST_EQUAL(B::compare(ul2, cu1), -1);
    /* lb=3=unbound  rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(uu1, cl2), 1);
    /* lb=3=unbound  rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(uu1, cl1), 1);
    /* lb=3=unbound  rb=1=closed   lu   !ru  */  //TEST_EQUAL(B::compare(uu2, cl1), 1);
    /* lb=3=unbound  rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(uu1, cu2), 1);
    /* lb=3=unbound  rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(uu1, cu1), 1);
    /* lb=3=unbound  rb=1=closed   lu   ru   */  //TEST_EQUAL(B::compare(uu2, cu1), 1);
    /* lb=3=unbound  rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(ul1, ol2), -1);
    /* lb=3=unbound  rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(ul1, ol1), -1);
    /* lb=3=unbound  rb=2=open     !lu  !ru  */  //TEST_EQUAL(B::compare(ul2, ol1), -1);
    /* lb=3=unbound  rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(ul1, ou2), -1);
    /* lb=3=unbound  rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(ul1, ou1), -1);
    /* lb=3=unbound  rb=2=open     !lu  ru   */  //TEST_EQUAL(B::compare(ul2, ou1), -1);
    /* lb=3=unbound  rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(uu1, ol2), 1);
    /* lb=3=unbound  rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(uu1, ol1), 1);
    /* lb=3=unbound  rb=2=open     lu   !ru  */  //TEST_EQUAL(B::compare(uu2, ol1), 1);
    /* lb=3=unbound  rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(uu1, ou2), 1);
    /* lb=3=unbound  rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(uu1, ou1), 1);
    /* lb=3=unbound  rb=2=open     lu   ru   */  //TEST_EQUAL(B::compare(uu2, ou1), 1);
    /* lb=3=unbound  rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(ul1, ul2), 0);
    /* lb=3=unbound  rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(ul1, ul1), 0);
    /* lb=3=unbound  rb=3=unbound  !lu  !ru  */  //TEST_EQUAL(B::compare(ul2, ul1), 0);
    /* lb=3=unbound  rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(ul1, uu2), -1);
    /* lb=3=unbound  rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(ul1, uu1), -1);
    /* lb=3=unbound  rb=3=unbound  !lu  ru   */  //TEST_EQUAL(B::compare(ul2, uu1), -1);
    /* lb=3=unbound  rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(uu1, ul2), 1);
    /* lb=3=unbound  rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(uu1, ul1), 1);
    /* lb=3=unbound  rb=3=unbound  lu   !ru  */  //TEST_EQUAL(B::compare(uu2, ul1), 1);
    /* lb=3=unbound  rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(uu1, uu2), 0);
    /* lb=3=unbound  rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(uu1, uu1), 0);
    /* lb=3=unbound  rb=3=unbound  lu   ru   */  //TEST_EQUAL(B::compare(uu2, uu1), 0);

}
