// This file is generated by the update-tests script

#include "test/unit-test.hpp"

void types_test_group() {
    UNIT_TEST(rs_interval_types_traits)
    UNIT_TEST(rs_interval_types_from_string)
    UNIT_TEST(rs_interval_types_to_string)
}

void continuous_arithmetic_test_group() {
    UNIT_TEST(rs_interval_continuous_contains_zero)
    UNIT_TEST(rs_interval_continuous_interval_reciprocal)
    UNIT_TEST(rs_interval_continuous_interval_arithmetic)
}

void continuous_basic_test_group() {
    UNIT_TEST(rs_interval_continuous_interval_basic_properties)
    UNIT_TEST(rs_interval_continuous_interval_construction)
    UNIT_TEST(rs_interval_continuous_interval_string_conversions)
    UNIT_TEST(rs_interval_continuous_interval_order)
    UNIT_TEST(rs_interval_continuous_interval_complement)
    UNIT_TEST(rs_interval_continuous_interval_binary_operations)
    UNIT_TEST(rs_interval_continuous_interval_hashing)
}

void continuous_boundary_addition_test_group() {
    UNIT_TEST(rs_interval_continuous_boundary_inversion)
    UNIT_TEST(rs_interval_continuous_boundary_addition)
    UNIT_TEST(rs_interval_continuous_boundary_subtraction)
}

void continuous_boundary_basic_test_group() {
    UNIT_TEST(rs_interval_continuous_boundary_formatting)
    UNIT_TEST(rs_interval_continuous_boundary_from_interval)
    UNIT_TEST(rs_interval_continuous_boundary_to_interval)
}

void continuous_boundary_comparison_test_group() {
    UNIT_TEST(rs_interval_continuous_boundary_adjacency)
    UNIT_TEST(rs_interval_continuous_boundary_comparison)
}

void continuous_boundary_multiplication_test_group() {
    UNIT_TEST(rs_interval_continuous_boundary_multiplication)
}

void continuous_map_test_group() {
    UNIT_TEST(rs_interval_continuous_interval_map)
}

void continuous_set_test_group() {
    UNIT_TEST(rs_interval_continuous_interval_set_construct_insert_erase)
    UNIT_TEST(rs_interval_continuous_interval_set_operations)
}

void integral_arithmetic_test_group() {
    UNIT_TEST(rs_interval_integral_contains_zero)
    UNIT_TEST(rs_interval_integral_interval_arithmetic)
}

void integral_basic_test_group() {
    UNIT_TEST(rs_interval_integral_interval_basic_properties)
    UNIT_TEST(rs_interval_integral_interval_construction)
    UNIT_TEST(rs_interval_integral_interval_string_conversions)
    UNIT_TEST(rs_interval_integral_interval_iterators)
    UNIT_TEST(rs_interval_integral_interval_order)
    UNIT_TEST(rs_interval_integral_interval_complement)
    UNIT_TEST(rs_interval_integral_interval_binary_operations)
    UNIT_TEST(rs_interval_integral_interval_hashing)
}

void integral_boundary_addition_test_group() {
    UNIT_TEST(rs_interval_integral_boundary_inversion)
    UNIT_TEST(rs_interval_integral_boundary_addition)
    UNIT_TEST(rs_interval_integral_boundary_subtraction)
}

void integral_boundary_basic_test_group() {
    UNIT_TEST(rs_interval_integral_boundary_formatting)
    UNIT_TEST(rs_interval_integral_boundary_from_interval)
    UNIT_TEST(rs_interval_integral_boundary_to_interval)
}

void integral_boundary_comparison_test_group() {
    UNIT_TEST(rs_interval_integral_boundary_adjacency)
    UNIT_TEST(rs_interval_integral_boundary_comparison)
}

void integral_boundary_multiplication_test_group() {
    UNIT_TEST(rs_interval_integral_boundary_multiplication)
}

void integral_map_test_group() {
    UNIT_TEST(rs_interval_integral_interval_map)
}

void integral_set_test_group() {
    UNIT_TEST(rs_interval_integral_interval_set_construct_insert_erase)
    UNIT_TEST(rs_interval_integral_interval_set_operations)
}

void ordered_basic_test_group() {
    UNIT_TEST(rs_interval_ordered_interval_basic_properties)
    UNIT_TEST(rs_interval_ordered_interval_construction)
    UNIT_TEST(rs_interval_ordered_interval_string_conversions)
    UNIT_TEST(rs_interval_ordered_interval_order)
    UNIT_TEST(rs_interval_ordered_interval_complement)
    UNIT_TEST(rs_interval_ordered_interval_binary_operations)
    UNIT_TEST(rs_interval_ordered_interval_hashing)
}

void ordered_boundary_basic_test_group() {
    UNIT_TEST(rs_interval_ordered_boundary_formatting)
    UNIT_TEST(rs_interval_ordered_boundary_from_interval)
}

void ordered_boundary_comparison_test_group() {
    UNIT_TEST(rs_interval_ordered_boundary_adjacency)
    UNIT_TEST(rs_interval_ordered_boundary_comparison)
}

void ordered_map_test_group() {
    UNIT_TEST(rs_interval_ordered_interval_map)
}

void ordered_set_test_group() {
    UNIT_TEST(rs_interval_ordered_interval_set_construct_insert_erase)
    UNIT_TEST(rs_interval_ordered_interval_set_operations)
}

void stepwise_basic_test_group() {
    UNIT_TEST(rs_interval_stepwise_interval_basic_properties)
    UNIT_TEST(rs_interval_stepwise_interval_construction)
    UNIT_TEST(rs_interval_stepwise_interval_string_conversions)
    UNIT_TEST(rs_interval_stepwise_interval_iterators)
    UNIT_TEST(rs_interval_stepwise_interval_order)
    UNIT_TEST(rs_interval_stepwise_interval_complement)
    UNIT_TEST(rs_interval_stepwise_interval_binary_operations)
    UNIT_TEST(rs_interval_stepwise_interval_hashing)
}

void stepwise_boundary_basic_test_group() {
    UNIT_TEST(rs_interval_stepwise_boundary_formatting)
    UNIT_TEST(rs_interval_stepwise_boundary_from_interval)
}

void stepwise_boundary_comparison_test_group() {
    UNIT_TEST(rs_interval_stepwise_boundary_adjacency)
    UNIT_TEST(rs_interval_stepwise_boundary_comparison)
}

void stepwise_map_test_group() {
    UNIT_TEST(rs_interval_stepwise_interval_map)
}

void stepwise_set_test_group() {
    UNIT_TEST(rs_interval_stepwise_interval_set_construct_insert_erase)
    UNIT_TEST(rs_interval_stepwise_interval_set_operations)
}

void version_test_group() {
    UNIT_TEST(rs_interval_version)
}

int main(int argc, char** argv) {

    RS::UnitTest::begin_tests(argc, argv);

    types_test_group();
    continuous_arithmetic_test_group();
    continuous_basic_test_group();
    continuous_boundary_addition_test_group();
    continuous_boundary_basic_test_group();
    continuous_boundary_comparison_test_group();
    continuous_boundary_multiplication_test_group();
    continuous_map_test_group();
    continuous_set_test_group();
    integral_arithmetic_test_group();
    integral_basic_test_group();
    integral_boundary_addition_test_group();
    integral_boundary_basic_test_group();
    integral_boundary_comparison_test_group();
    integral_boundary_multiplication_test_group();
    integral_map_test_group();
    integral_set_test_group();
    ordered_basic_test_group();
    ordered_boundary_basic_test_group();
    ordered_boundary_comparison_test_group();
    ordered_map_test_group();
    ordered_set_test_group();
    stepwise_basic_test_group();
    stepwise_boundary_basic_test_group();
    stepwise_boundary_comparison_test_group();
    stepwise_map_test_group();
    stepwise_set_test_group();
    version_test_group();

    return RS::UnitTest::end_tests();

}
