#!/usr/bin/env bash

set -euo pipefail

dir="${PWD##*/}"
dir="${dir%%-*}"
if [ "$dir" == build ]; then cd ..; fi

head=$(find source -name unit-test.hpp)
if ! [ "$head" ]; then
    echo "*** unit-test.hpp not found"
    exit 1
fi

main=$(find source -name unit-test.cpp)
if ! [ "$main" ]; then
    echo "*** unit-test.cpp not found"
    exit 1
fi
temp="${main%.cpp}.temp.cpp"

cmake=$(find source -name CMakeLists.txt)
if ! [ "$cmake" ]; then
    echo "*** CMakeLists.txt not found"
    exit 1
fi

testfiles=$(grep -E '[-]test\.cpp$' "$cmake" \
    | sed -E 's!^ +!source/!' \
    | grep -Fv "$main")

cat > $temp << EOF
#include "${head#source/}"

int main(int argc, char** argv) {

    RS::UnitTest::begin_tests(argc, argv);

EOF

for file in $testfiles; do
    if [ -f $file ]; then
        echo "    // ${file##*/}" >> $temp
        grep -Eh '^void test_' $file \
            | sed -E 's/^void test_([a-z0-9_]+)\(\).*$/\1/' \
            | grep -Ev '^void ' \
            | sed -E 's/.+/    UNIT_TEST(&)/' \
            >> $temp \
            || true
        echo >> $temp
    fi
done

cat >> $temp << EOF
    return RS::UnitTest::end_tests();

}
EOF

if cmp -s $temp $main; then
    rm $temp
else
    mv $temp $main
fi
