// This file is generated by the rs-bump-version script

#pragma once

#include <string>
#include <array>

namespace RS::Intervals {

    inline std::array<int, 3> version() noexcept {
        return {{ 0, 1, 25 }};
    }

    inline std::string version_string() {
        return "0.1.25";
    }

}
